import type { DashboardPayload } from "./types";

/** Dados de exemplo — substituídos quando `GET /api/dashboard` responder. */
export function getMockDashboard(): DashboardPayload {
  const now = new Date();
  return {
    updatedAt: now.toISOString(),
    summary: {
      vendas: 26,
      vendasAtMorning: 12,
      revenue: 5980,
      gasto: 3230,
      gastoAtMorning: 935,
      profit: 2750,
      roas: 1.85,
      cpa: 124,
      avgOrderValue: 230,
      metaRoas: 1.5,
      metaCpa: 130,
    },
    comparison: [
      {
        label: "Terça",
        dateLabel: "24/03",
        vendas: 31,
        gasto: 2980,
        profit: 4150,
        roas: 2.39,
        cpa: 96,
        partial: false,
      },
      {
        label: "Quarta",
        dateLabel: "25/03",
        vendas: 28,
        gasto: 3120,
        profit: 3320,
        roas: 2.06,
        cpa: 111,
        partial: false,
      },
      {
        label: "Hoje",
        dateLabel: "26/03",
        vendas: 26,
        gasto: 3230,
        profit: 2750,
        roas: 1.85,
        cpa: 124,
        partial: true,
      },
    ],
    accounts: [
      {
        id: "1",
        conta: "C01 EUA",
        nicho: "Diabetes",
        gasto: 890,
        conv: 8,
        ic: 14,
        revenue: 1840,
        daysRunning: 12,
      },
      {
        id: "2",
        conta: "C06 Aurora",
        nicho: "WL",
        gasto: 420,
        conv: 5,
        ic: 9,
        revenue: 1150,
        daysRunning: 2,
      },
      {
        id: "3",
        conta: "C03 EUA",
        nicho: "Joint Pain",
        gasto: 1100,
        conv: 3,
        ic: 18,
        revenue: 690,
        daysRunning: 5,
      },
      {
        id: "4",
        conta: "C09 BR",
        nicho: "WL",
        gasto: 280,
        conv: 0,
        ic: 7,
        revenue: 0,
        daysRunning: 1,
      },
      {
        id: "5",
        conta: "C11 EUA",
        nicho: "Diabetes",
        gasto: 540,
        conv: 10,
        ic: 15,
        revenue: 2300,
        daysRunning: 8,
      },
    ],
  };
}
