import type {
  RepriceDashboardDay,
  RepriceDashboardSummary,
  RepriceListingRow,
  RepriceOrderRow,
  RepriceStrategyRow,
  RepriceTemplateRow,
} from "./types";

function daysBack(n: number): string {
  const d = new Date();
  d.setDate(d.getDate() - n);
  return d.toISOString().slice(0, 10);
}

/** Série diária sintética (últimos 30 dias). */
export const mockRepriceDashboardSeries: RepriceDashboardDay[] = Array.from({ length: 30 }, (_, i) => {
  const t = 29 - i;
  const base = 800 + Math.sin(i / 4) * 400 + (i % 7) * 120;
  return {
    day: daysBack(t),
    revenue: Math.round(base * 100) / 100,
    sales: Math.max(1, Math.round(8 + (i % 5) * 2 + Math.sin(i) * 3)),
    buyBoxPct: Math.round((68 + (i % 4) * 2 + Math.sin(i / 3) * 4) * 100) / 100,
    profitMarginPct: Math.round((3.5 + (i % 3) * 0.4) * 100) / 100,
    profit: Math.round(base * 0.22 * 100) / 100,
  };
});

export const mockRepriceDashboardSummary: RepriceDashboardSummary = {
  revenueUsd: 25106.45,
  salesCount: 424,
  buyBoxPct: 73.86,
  profitUsd: 7175.21,
  activeListings: 318,
  outOfStockListings: 17,
  inBuyBox: 273,
  competitionBelowMin: 5,
  supplierMix: [
    { supplier: "walmart", label: "Walmart", count: 210 },
    { supplier: "sams", label: "Sam's Club", count: 95 },
    { supplier: "other", label: "Outros", count: 13 },
  ],
};

export const mockRepriceListings: RepriceListingRow[] = [
  {
    id: "1",
    title: "9 Qt TriZone Dual Basket Air Fryer",
    sku: "WM-AF-9QT-01",
    asin: "B0GM8NHMBW",
    supplier: "walmart",
    supplierLabel: "Walmart",
    supplierPrice: 159,
    supplierShipping: 0,
    bundleQty: 1,
    qty: 30,
    amazonPrice: 265,
    lowestPrice: 265,
    buyBoxPrice: 265,
    buyBoxEligible: "yes",
    minPrice: 265,
    maxPrice: 265.04,
    profit: 66.25,
    strategyId: "s3",
    strategyLabel: "35% margem",
    orderCount: 12,
  },
  {
    id: "2",
    title: "2 Pack Pineapple Spears in Juice",
    sku: "WM-PIN-2P",
    asin: "B08N5WRWNW",
    supplier: "walmart",
    supplierLabel: "Walmart",
    supplierPrice: 4.5,
    supplierShipping: 0,
    bundleQty: 1,
    qty: 0,
    amazonPrice: 14.99,
    lowestPrice: 13.5,
    buyBoxPrice: 13.5,
    buyBoxEligible: "no",
    minPrice: 12,
    maxPrice: 16,
    profit: 4.1,
    strategyId: "s2",
    strategyLabel: "25% margem",
    orderCount: 44,
  },
  {
    id: "3",
    title: "Stainless Steel Water Bottle 40oz",
    sku: "SC-BTL-40",
    asin: "B0DUMMY01",
    supplier: "sams",
    supplierLabel: "Sam's Club",
    supplierPrice: 18,
    supplierShipping: 0,
    bundleQty: 1,
    qty: 14,
    amazonPrice: 36.5,
    lowestPrice: 35,
    buyBoxPrice: 35.99,
    buyBoxEligible: "yes",
    minPrice: 32,
    maxPrice: 39.99,
    profit: 9.2,
    strategyId: "s1",
    strategyLabel: "Buy Box",
    orderCount: 7,
  },
];

export const mockRepriceOrders: RepriceOrderRow[] = [
  {
    id: "o1",
    purchaseAtIso: "2026-04-17T14:22:00.000Z",
    status: "pending",
    title: "2 Pack Pineapple Spears in Juice",
    sku: "WM-PIN-2P",
    asin: "B08N5WRWNW",
    amazonOrderId: "111-1234567-8901234",
    supplier: "walmart",
    supplierLabel: "Walmart",
    amazonPrice: 14.99,
    amazonFee: 2.25,
    amazonShipping: 0,
    qtySold: 1,
    supplierPrice: 4.5,
    supplierTax: 0.36,
    supplierDiscount: 0,
    supplierShipping: 0,
    profit: 7.88,
    profitMarginPct: 52.5,
  },
  {
    id: "o2",
    purchaseAtIso: "2026-04-16T09:10:00.000Z",
    status: "shipped",
    title: "9 Qt TriZone Dual Basket Air Fryer",
    sku: "WM-AF-9QT-01",
    asin: "B0GM8NHMBW",
    amazonOrderId: "111-9876543-2109876",
    supplier: "walmart",
    supplierLabel: "Walmart",
    amazonPrice: 265,
    amazonFee: 39.75,
    amazonShipping: 0,
    qtySold: 1,
    supplierPrice: 159,
    supplierTax: 12.72,
    supplierDiscount: 0,
    supplierShipping: 0,
    profit: 53.53,
    profitMarginPct: 20.2,
  },
  {
    id: "o3",
    purchaseAtIso: "2026-04-15T18:00:00.000Z",
    status: "canceled",
    title: "Stainless Steel Water Bottle 40oz",
    sku: "SC-BTL-40",
    asin: "B0DUMMY01",
    amazonOrderId: "111-0000000-0000001",
    supplier: "sams",
    supplierLabel: "Sam's Club",
    amazonPrice: 36.5,
    amazonFee: 5.48,
    amazonShipping: 0,
    qtySold: 1,
    supplierPrice: 18,
    supplierTax: 1.44,
    supplierDiscount: 0,
    supplierShipping: 0,
    profit: 11.58,
    profitMarginPct: 31.7,
  },
];

export const mockRepriceStrategies: RepriceStrategyRow[] = [
  {
    id: "s1",
    name: "Buy Box",
    competitionMode: "match",
    strategyTarget: "buy_box",
    whenNoCompetition: "no_change",
    sellerRatingMin: null,
    amountValue: 0,
    amountUnit: "pct",
    minProfitPct: 10,
    maxProfitPct: 10.01,
    listingsAssigned: 12,
  },
  {
    id: "s2",
    name: "25% margem",
    competitionMode: "below",
    strategyTarget: "lowest",
    whenNoCompetition: "lowest",
    sellerRatingMin: null,
    amountValue: 0.01,
    amountUnit: "usd",
    minProfitPct: 25,
    maxProfitPct: 25.01,
    listingsAssigned: 74,
  },
  {
    id: "s3",
    name: "35% margem",
    competitionMode: "match",
    strategyTarget: "buy_box",
    whenNoCompetition: "no_change",
    sellerRatingMin: null,
    amountValue: 0,
    amountUnit: "usd",
    minProfitPct: 35,
    maxProfitPct: 35.01,
    listingsAssigned: 271,
  },
];

export const mockRepriceTemplates: RepriceTemplateRow[] = [
  {
    id: "t1",
    name: "Walmart",
    profitPct: 25,
    amazonFeePct: 15,
    supplierShippingUsd: 9,
    supplierTaxPct: 0,
    supplierDiscountPct: 0,
    bundleQty: 1,
    handlingDays: 2,
    defaultQty: 30,
    restockQty: true,
    repriceOnAmazon: true,
    oosZeroQty: true,
  },
];
